Models/Warrant.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Ticket.Models
{
    public class Warrant
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime ExpireDate { get; set; }
        public bool IsDeleted { get; set; }
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
    }
}

Areas/AdminPanel/Controllers/WarrantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ticket.Areas.AdminPanel.ViewModels;
using Ticket.DAL;
using Ticket.Models;
using X.PagedList;

namespace Ticket.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize(Roles = "Admin")]
    public class WarrantController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        public WarrantController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            List<WarrantVMA> tickets = new List<WarrantVMA>();
            try
            {
                foreach (Warrant item in await _context.Warrants.Include(x => x.Category).ToListAsync())
                {
                    WarrantVMA warrant = new WarrantVMA
                    {
                        Id = item.Id,
                        Name = item.Name,
                        IsDeleted = item.IsDeleted,
                        Price = item.Price,
                        Category = item.Category.Name
                    };
                    tickets.Add(warrant);
                };
                return View(tickets.ToPagedList(page, 8));
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> WarrantAdd()
        {
            try
            {
                List<CategoryComboBoxVM> list = new List<CategoryComboBoxVM>();
                foreach (Category item in await _context.Categories.Where(x=>x.IsDeleted==false).ToListAsync())
                {
                    CategoryComboBoxVM data = new CategoryComboBoxVM
                    {
                        CategoryId = item.Id,
                        CategoryName = item.Name
                    };
                    list.Add(data);
                }
                ViewBag.CategoryList = list;
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        public async Task<IActionResult> WarrantAdd(WarrantAddVM warrantVM)
        {
            try
            {
                if (warrantVM != null)
                {
                    Warrant warrant = new Warrant
                    {
                        Name = warrantVM.Name,
                        CategoryId = warrantVM.CategoryId,
                        Price = warrantVM.Price,
                        CreateDate = warrantVM.CreateDate,
                        ExpireDate = warrantVM.ExpireDate,
                        Description = warrantVM.Description,
                        IsDeleted = false
                    };
                    await _context.Warrants.AddAsync(warrant);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("WarrantAdd", warrantVM);
            }
        }

        [HttpGet]
        public async Task<IActionResult> WarrantEdit(int id)
        {
            try
            {
                Warrant warrant = await _context.Warrants.FindAsync(id);
                if (warrant != null)
                {
                    WarrantAddVM warrantVM = new WarrantAddVM
                    {
                        CategoryId = warrant.CategoryId,
                        Description = warrant.Description,
                        CreateDate = warrant.CreateDate,
                        ExpireDate = warrant.ExpireDate,
                        Name = warrant.Name,
                        Price = warrant.Price,
                        Id = warrant.Id
                    };
                    List<CategoryComboBoxVM> list = new List<CategoryComboBoxVM>();
                    foreach (Category item in await _context.Categories.Where(x => x.IsDeleted == false).ToListAsync())
                    {
                        CategoryComboBoxVM data = new CategoryComboBoxVM
                        {
                            CategoryId = item.Id,
                            CategoryName = item.Name
                        };
                        list.Add(data);
                    }
                    ViewBag.CategoryList = list;
                    return View(warrantVM);
                }
                else
                    return View(new WarrantAddVM());
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> WarrantEdit(WarrantAddVM editedWarrant)
        {
            try
            {
                if (editedWarrant != null)
                {
                    Warrant warrant = await _context.Warrants.FindAsync(editedWarrant.Id);
                    warrant.Price = editedWarrant.Price;
                    warrant.Name = editedWarrant.Name;
                    warrant.Description = editedWarrant.Description;
                    warrant.CategoryId = editedWarrant.CategoryId;
                    warrant.CreateDate = editedWarrant.CreateDate;
                    warrant.ExpireDate = editedWarrant.ExpireDate;
                    _context.Warrants.Update(warrant);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("WarrantEdit", editedWarrant);
            }
        }

        public async Task<JsonResult> WarrantDetails(int id)
        {
            try
            {
                Warrant warrant = await _context.Warrants.Include(x => x.Category).FirstOrDefaultAsync(x => x.Id == id);
                WarrantInfoVM warrantInfo = new WarrantInfoVM()
                {
                    Id = warrant.Id,
                    Price = warrant.Price,
                    Name = warrant.Name,
                    Description = warrant.Description.Length > 150 ? warrant.Description.Substring(0, 150) : warrant.Description,
                    Category = warrant.Category.Name,
                    CreateDate = warrant.CreateDate,
                    ExpireDate = warrant.ExpireDate,
                    IsDeleted = warrant.IsDeleted
                };
                string data = JsonConvert.SerializeObject(warrantInfo);
                return Json(data);
            }
            catch (Exception)
            {
                WarrantInfoVM warrant = new WarrantInfoVM()
                {
                    Id = 1,
                    CreateDate = DateTime.Now,
                    ExpireDate = DateTime.Now,
                    Category = "Xeta",
                    Description = "Xeta",
                    IsDeleted = true,
                    Name = "Xeta",
                    Price = 0
                };
                string data = JsonConvert.SerializeObject(warrant);
                return Json(data);
            }
        }

        [HttpPost]
        public async Task<JsonResult> DeleteWarrant(int id)
        {
            try
            {
                Warrant warrant = await _context.Warrants.FindAsync(id);
                warrant.IsDeleted = true;
                _context.Warrants.Update(warrant);
                await _context.SaveChangesAsync();
                return Json("Success");
            }
            catch (Exception)
            {
                return Json("Fail");
            }
        }

        [HttpPost]
        public async Task<JsonResult> ActivateWarrant(int id)
        {
            try
            {
                Warrant warrant = await _context.Warrants.FindAsync(id);
                warrant.IsDeleted = false;
                _context.Warrants.Update(warrant);
                await _context.SaveChangesAsync();
                return Json("Success");
            }
            catch (Exception)
            {
                return Json("Fail");
            }
        }
    }
}

Areas/AdminPanel/Views/Warrant/Index.cshtml
@model IPagedList<WarrantVMA>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="pt-3">
    <div class="table-bg">
        <div class="card-header-custom">
            <h3>Biletlər</h3>
            <a href="/AdminPanel/Warrant/WarrantAdd" class="btn custom-admin-button"><span>Yeni Bilet</span> <i class='bx bxs-book-add'></i></a>
        </div>
        <div class="card-body mt-2">
            <div class="table-responsive">
                <table class="table-custom" style="width: 100%;">
                    <thead class="thead-custom">
                        <tr>
                            <td>Adı</td>
                            <td>Kateqoriyası</td>
                            <td>Qiymət</td>
                            <td>Status</td>
                            <td>Əməliyyatlar</td>
                        </tr>
                    </thead>
                    <tbody class="tbody-custom">
                        @foreach(var item in Model)
                        {
                            <tr>
                                <td class="my-table-data">@item.Name</td>
                                <td class="my-table-data">@item.Category</td>
                                <td class="my-table-data">@item.Price AZN</td>
                                <td id="table-data-@item.Id">
                                    @if (!item.IsDeleted)
                                    {
                                        <span class="status green"></span><span> Aktiv</span>
                                    }
                                    else
                                    {
                                        <span class="status red"></span>
                                        <a onclick="activateWarrant(@item.Id)" class="btn btn-outline-success">Aktiv et</a>
                                    }
                                </td>
                                <td class="d-flex justify-content-between">
                                    <button class="btn btn-dark" onclick="WarrantDetails(@item.Id)"><i class='bx bxs-detail'></i></button>
                                    <a class="btn btn-dark" href="/AdminPanel/Warrant/WarrantEdit/@item.Id"><i class='bx bxs-edit' ></i></a>
                                    <button type="button" onclick="delWarrant(@item.Id)" class="btn btn-dark"><i class='bx bxs-trash' ></i></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", "Warrant", new { page }), new PagedListRenderOptions
{
    PageClasses = new string[] { "page-link bg-dark text-light border-dark" },
    LiElementClasses = new string[] { "page-item" },
    DisplayLinkToLastPage = PagedListDisplayMode.Always,
    DisplayLinkToFirstPage = PagedListDisplayMode.Always,
    ContainerDivClasses = new string[] { "p-1 pt-3" },
    ActiveLiElementClass = "active-page"
})

@section scripts {
    <script>
        function delWarrant(ticket_id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger me-3'
                },
                buttonsStyling: false
            })

            swalWithBootstrapButtons.fire({
                title: 'Əminsiniz?',
                text: "İstədiyin vaxt bu Bileti aktiv edə bilərsən!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Bəli, bunu sil!',
                cancelButtonText: 'Xeyr, ləğv et!',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {
                    let timerInterval
                    Swal.fire({
                        title: 'Silinir...!',
                        html: 'Bunu <b></b> millisaniyələr ərzində siləcəm.',
                        timer: 1000,
                        timerProgressBar: true,
                        didOpen: () => {
                            $.ajax({
                                type: 'POST',
                                url: '/AdminPanel/Warrant/DeleteWarrant/',
                                data: { id: ticket_id }
                            });
                            Swal.showLoading()
                            const b = Swal.getHtmlContainer().querySelector('b')
                            timerInterval = setInterval(() => {
                                b.textContent = Swal.getTimerLeft()
                            }, 100)
                        },
                        willClose: () => {
                            clearInterval(timerInterval)
                        }
                    }).then((result) => {
                        Swal.fire({
                            icon: 'success',
                            title: 'Silindi!',
                            text: 'Bu bilet uğurla silindi!'
                        });
                        document.getElementById("table-data-" + ticket_id).innerHTML = `<span class="status red"></span>
                                            <a onclick="activateWarrant(${ticket_id})" class="btn btn-outline-success">Aktiv et</a>`;
                    });
                } else if (
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Ləğv edildi',
                        'Bilet qurtarıldı :)',
                        'error'
                    )
                }
            })
        }

        function activateWarrant(ticket_id) {
            let timerInterval
            Swal.fire({
                title: 'Aktiv edilir...!',
                html: 'Bunu <b></b> millisaniyələr ərzində aktiv edəcəm.',
                timer: 1000,
                timerProgressBar: true,
                didOpen: () => {
                    $.ajax({
                        type: 'POST',
                        url: '/AdminPanel/Warrant/ActivateWarrant/',
                        data: { id: ticket_id }
                    });
                    Swal.showLoading()
                    const b = Swal.getHtmlContainer().querySelector('b')
                    timerInterval = setInterval(() => {
                        b.textContent = Swal.getTimerLeft()
                    }, 100)
                },
                willClose: () => {
                    clearInterval(timerInterval)
                }
            }).then((result) => {
                Swal.fire({
                    icon: 'success',
                    title: 'Aktiv edildi!',
                    text: 'Bilet uğurla aktiv edildi!'
                });
                document.getElementById("table-data-" + ticket_id).innerHTML = `<span class="status green"></span><span> Aktiv</span>`;
            });
        }

        function WarrantDetails(ticket_id) {
            $(function () {
                $.ajax({
                    contentType: 'application/json',
                    dataType: 'json',
                    type: 'GET',
                    url: '/AdminPanel/Warrant/WarrantDetails/',
                    data: { id: ticket_id },
                    success: function (myvalue) {
                        let data = jQuery.parseJSON(myvalue);
                        Swal.fire({
                            title: `<div class="text-center">Biletin detalları</div>`,
                            html:
                                `<h4 class="text-info"><b>#${data.Id} - ${data.Name}</b></h4>
                                    <h6 class="text-warning"><span>Qiymət : ${data.Price} AZN</span></h6>
                                    <hr>
                                    <h6><span>${data.Description}</span></h6>
                                    <hr>
                                    <h6><span>Kateqoriya : ${data.Category}</span></h6>
                                    <h6 class="text-muted"> Başlanğıc Tarixi : ${data.CreateDate.replace('T',' ')}</h6>
                                    <h6 class="text-muted"> Bitiş Tarixi : ${data.ExpireDate.replace('T',' ')}</h6>
                                    <hr>
                                    <h6 class="text-info"> Status : ${data.IsDeleted ?'DeAktiv':'Aktiv'}</h6>`,
                            showCloseButton: true,
                            showCancelButton: true,
                            focusConfirm: false,
                            confirmButtonText:
                                `<a class="text-white nav-link p-0" href="/AdminPanel/Warrant/WarrantEdit/${ticket_id}"><i class='bx bxs-edit'></i> Bileti düzənlə</a>`,
                            confirmButtonAriaLabel: 'Edit',
                            cancelButtonText:
                                '<span><i class="bx bxs-left-arrow-circle" ></i> Oldu</span>',
                            cancelButtonAriaLabel: 'Okay'
                        });
                    }
                })
            });
        }
    </script>
}

Areas/AdminPanel/Views/Warrant/WarrantAdd.cshtml
@model WarrantAddVM

@{
    ViewData["Title"] = "WarrantAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container p-4">
    <div class="bg-light white-card">
        <div>
            <div class="text-center p-3">
                <h1>Yeni Bilet yarat</h1>
            </div>
            <div class="pt-4">
                <form method="post">
                    <div class="p-3">
                        <label for="tb-title">Bilet adı</label>
                        <input id="tb-title" asp-for="Name" class="form-control" type="text" placeholder="Bilet adı..." required />
                    </div>
                    <div class="p-3">
                        <label for="tb-price">Qiymət</label>
                        <input id="tb-price" asp-for="Price" step="0.01" class="form-control" type="number" placeholder="00.000 AZN" required />
                    </div>
                    <div class="p-3">
                        <label class="d-block" for="tb-cr-date">Başlanğıc tarixi</label>
                        <input id="tb-cr-date" asp-for="CreateDate" class="form-control input-custom-date" type="datetime-local" required />
                        <button class="btn btn-dark btn-now" onclick="timestampToDatetimeInputString('tb-cr-date')" >Indi</button>
                    </div>
                    <div class="p-3 w-100">
                        <label class="d-block" for="tb-exp-date">Bitiş tarixi</label>
                        <input id="tb-exp-date" asp-for="ExpireDate" class="form-control input-custom-date" type="datetime-local" required />
                        <button class="btn btn-dark btn-now" onclick="timestampToDatetimeInputString('tb-exp-date')" >Indi</button>
                    </div>
                    <div class="p-3">
                        <label for="selection" class="m-auto">Kateqoriya</label>
                        <select id="selection" class="form-group form-control col-md-12 mt-2" asp-for="CategoryId">
                            @foreach (var item in ViewBag.CategoryList)
                            {
                                <option class="form-control" value="@item.CategoryId">@item.CategoryName</option>
                            }
                        </select>
                    </div>
                    <div class="p-3">
                        <label for="tb-content">Biletin açıqlaması</label>
                        <textarea id="tb-content" asp-for="Description" class="form-control" rows="10" placeholder="Biletin açıqlaması..." required></textarea>
                    </div>
                    <div class="text-center p-3">
                        <button type="button" onclick="window.location.href='/AdminPanel/Warrant/Index'" class="custom-admin-cancel">Ləğv et</button>
                        <button type="submit" id="btn-save" class="custom-admin-button">Yarat</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
        function timestampToDatetimeInputString(id1)
        {
            var now = new Date();
            now.setMinutes(now.getMinutes() - now.getTimezoneOffset());
            document.getElementById(id1).value = now.toISOString().slice(0, 16);
        }
</script>

Areas/AdminPanel/Views/Warrant/WarrantEdit.cshtml
@model WarrantAddVM

@{
    ViewData["Title"] = "WarrantEdit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container p-4">
    <div class="bg-light white-card">
        <div>
            <div class="text-center p-3">
                <h1>Bileti düzənlə</h1>
            </div>
            <div class="pt-4">
                <form method="post">
                    <div class="p-3">
                        <label for="tb-title">Bilet adı</label>
                        <input id="tb-title" asp-for="Name" class="form-control" type="text" placeholder="Bilet adı..." required />
                    </div>
                    <div class="p-3">
                        <label for="tb-price">Qiymət</label>
                        <input id="tb-price" asp-for="Price" step="0.01" class="form-control" type="number" placeholder="00.000 AZN" required />
                    </div>
                    <div class="p-3">
                        <label class="d-block" for="tb-cr-date">Başlanğıc tarixi</label>
                        <input id="tb-cr-date" asp-for="CreateDate" class="form-control input-custom-date" type="datetime-local" required />
                        <button class="btn btn-dark btn-now" onclick="timestampToDatetimeInputString('tb-cr-date')" >Indi</button>
                    </div>
                    <div class="p-3 w-100">
                        <label class="d-block" for="tb-exp-date">Bitiş tarixi</label>
                        <input id="tb-exp-date" asp-for="ExpireDate" class="form-control input-custom-date" type="datetime-local" required />
                        <button class="btn btn-dark btn-now" onclick="timestampToDatetimeInputString('tb-exp-date')" >Indi</button>
                    </div>
                    <div class="p-3">
                        <label for="selection" class="m-auto">Kateqoriya</label>
                        <select id="selection" class="form-group form-control col-md-12 mt-2" asp-for="CategoryId">
                            @foreach (var item in ViewBag.CategoryList)
                            {
                                <option class="form-control" value="@item.CategoryId">@item.CategoryName</option>
                            }
                        </select>
                    </div>
                    <div class="p-3">
                        <label for="tb-content">Biletin açıqlaması</label>
                        <textarea id="tb-content" asp-for="Description" class="form-control" rows="10" placeholder="Biletin açıqlaması..." required></textarea>
                    </div>
                    <div class="text-center p-3">
                        <button type="button" onclick="window.location.href='/AdminPanel/Warrant/Index'" class="custom-admin-cancel">Ləğv et</button>
                        <button type="submit" id="btn-save" class="custom-admin-button">Tətbiq et</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
        function timestampToDatetimeInputString(id1)
        {
            var now = new Date();
            now.setMinutes(now.getMinutes() - now.getTimezoneOffset());
            document.getElementById(id1).value = now.toISOString().slice(0, 16);
        }
</script>